default:

  # URL for getting project data
  ef_pubxls_url: "https://dotaceeu.cz/getmedia/6297d56b-0b57-418d-ad25-dd16bd687479/2021_06-Seznam-operaci-_-List-of-operations.xls.aspx?ext=.xls"

  # sestavy from MS
  sest_dir: "data-input/sestavy 20210528"
  sest_xlsx_prj: "E001 Identifikace projektu.xlsx"
  sest_xlsx_fin: "E003 Finance celkem.xlsx"
  sest_xlsx_zop: "E004 Žádosti o platbu.xlsx"
  sest_xlsx_obl: "E005 Kategorizace_oblast.xlsx"

  # PRV data-input

  prv_data_path: "data-input/prv/PRV 2014-20 k XII. 2020.XLSX"

  # Quest/Hermin categorisations
  mc_xlsx_q: "data-input/kategorizace/kategorie_questNEW-2.xlsx"
  mc_xlsx_h: "data-input/kategorizace/AIS_desagregace_rHERMIN.xlsx"
  mc_xlsx_prv: "data-input/kategorizace/Navrh - KATEGORIZACE - Operace PRV + priority.xlsx"

  # Arrow directory of cleaned up geolocation data for projects
  ef_obce_arrowdir: "data-input/esif-projekty-obce"

  # Excel file with hierarchy of all objectives and categories
  hier_excel_path: "data-input/matice/Hierarchie_uprava_CSR_NPR-O27-uprava_20210125.xlsx"
  hier_excel_sheet: SC

  # IDs
  czso_pop_table_id: "130149"

  # Input data paths - 2007-13 data
  sest_7_input_dir_orig: "data-input/sestavy 2007-13 orig"
  sest_7_prj: "Prehled_projektu_20170405.xlsx"
  sest_7_platby: "Platby_Chl_Nov_bez filtru.csv"
  sest_7_nuts3: "07-13_realizace v NUTS3.xlsx"
  sest_7_kat: "Prehled_projektu_prioritni_tema_2017.xlsx"
  cis_7_op: "ciselniky/ciselnik_programy2007.xlsx"
  cis_7_nuts3: "ciselniky/nuts3convert.csv"

  macrocat_7: "data-input/kategorizace/kategorie_0713.xlsx"

  sest_7_input_dir_new: "data-input/sestavy 2007-13 20211126"
  sest_7_katekon: ["211026_kategorizace7.xlsx", "211026_kategorizace8.xlsx"]

  # export location - 2007-13
  export_0713_dir: "data-export/export_0713_202111"
  export_0713_prj_pq: "prj_tema-nuts-ekonkat_0713.parquet"
  export_0713_detail_xlsx:  "makro_detail_0713.xlsx"
  export_0713_detail_csv: "makro_detail_0713_0713.csv"
  export_0713_detail_pq: "makro_detail_0713_0713.parquet"
  export_0713_csv: "makro_0713.csv"
  export_0713_xlsx: "makro_0713.xlsx"
  export_0713_pq: "makro_0713.parquet"

  export_0713_kategorie: "kategorie_0713.xlsx"

  export_0713_cdbk: "sum_0713_codebook.yaml"

  # export location - macro
  macro_export_dir: "data-export/export_202108"

  macro_export_reg_xlsx_a: "macro-sum_reg_quarterly.xlsx"
  macro_export_reg_xlsx_q: "macro-sum_reg_annual.xlsx"
  macro_export_reg_csv_a: "macro-sum_reg_quarterly.csv"
  macro_export_reg_csv_q: "macro-sum_reg_annual.csv"

  macro_export_xlsx_a: "macro-sum_quarterly.xlsx"
  macro_export_xlsx_q: "macro-sum_annual.xlsx"
  macro_export_csv_a: "macro-sum_quarterly.csv"
  macro_export_csv_q: "macro-sum_annual.csv"

  macro_export_cdbk: "macro-sum_codebook.yaml"

  repo_remote: "https://github.com/petrbouchal/esifunguji"

  # export location - hierarchy
  hier_export_dir: "data-export/matice_202108"
  hier_export_xlsx: "matice.xlsx"
