default:

  # settings for MISRIS (central budget starting from 2015)
  sp_years_central_new: !expr 2015:2020 # which years to download
  sp_months_central_new: 12 # which month's data to download
  sp_central_arrowdir_new: "data-processed/sp-central-new-arr"

  c_ef_obce_arrowdir: "data-input/esif-projekty-obce"

  # settings for FINU (central budget 2010-2014)
  sp_years_central_old: !expr 2010:2014
  sp_months_central_old: 12
  sp_central_arrowdir_old: "data-processed/sp-central-old-arr"

  # settings for FINM (local budget 2010-2014)
  sp_years_local: !expr 2010:2020
  sp_months_local: 12
  sp_local_arrowdir: "data-processed/sp-local-arr"
  sp_local_grants_arrowdir: "data-processed/sp-local-grants-arr"

  # URL for getting project data
  doteu_xls_url: https://dotaceeu.cz/getmedia/6043cc3d-ca8c-4866-ba4a-25d0184d1269/2021_02-Seznam-operaci-_List-of-operations_1.xls.aspx?ext=.xls
