---
title: "New site"
lang: cs
---

```{r setup, include=F}

knitr::opts_chunk$set(echo = F, eval = T, warning = F, out.width = "90%", message = F)

knitr::opts_knit$set()

library(stringr)
library(dplyr)
library(ggplot2)
# library(CzechData)
library(lubridate)
library(ragg)
library(ptrr)
library(scales)
library(fontawesome)
library(tidyverse)
library(targets)
library(arrow)

Sys.setlocale("LC_TIME", "cs_CZ.UTF-8")

ptrr::set_geom_defaults()
```

```{r fonts}
sysfonts::font_add_google("IBM Plex Sans", "IBM Plex Sans")
sysfonts::font_add_google("IBM Plex Sans Condensed", "IBM Plex Sans Condensed")
```

```{r metathis}
library(metathis)

meta() %>%
  meta_description(
    "Description"
  ) %>% 
  meta_name("github-repo" = "petrbouchal/...") %>% 
  meta_viewport() %>% 
  meta_social(
    title = "Social title",
    url = "https://petrbouchal.xyz/.../",
    image = "https://petrbouchal.xyz/.../twitter_card_large.png",
    image_alt = "Image alt",
    og_type = "website",
    og_author = c("Petr Bouchal"),
    twitter_card_type = "summary_large_image",
    twitter_creator = "@petrbouchal"
  )
```

# {.tabset}

## Tab 1 {.tabset .tabset-pills} 

```{r tab1}
ds <- arrow::open_dataset(targets::tar_read(sp_central_old_arrdir))
```

```{r}
ds
```


### Subtab 1


```{r subtab2}
library(ggplot2)

ggplot(mtcars) +
  geom_point(aes(mpg, wt)) +
  ggtitle("Abc 123 xyx") +
  theme_ptrr()
```

"Hello"

### Subtab 2

## Data & disclaimer

Text

# 

Last built on `r format(lubridate::now("CET"), "%Y-%m-%d %H:%M %Z")`
