---
title: esifunguji
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# macro-esif-budget

<!-- badges: start -->
<!-- badges: end -->

Tento repozitář obsahuje kód na zpracování dat o výdajích financovaných z ESI fondů v ČR primárně v letech 2014-2020. Cílem je:

- sestavit dataset použitelný pro modelování dopadů ESI fondů na HDP (QUEST, HERMIN - tj. republiková a krajská úroveň, kategorizace výdajů podle specifikace modelů)
- ověřit spolehlivost dat státní pokladny o zdrojích veřejných výdajů (u výdajů ústředních orgánů informace o zdroji, u místně řízených organizací informace o přijatých transferech)
- připravit dataset pro vyhodnocení role ESI fondů ve veřejných výdajích
- [buď zde nebo jinde] analýza role ESI fondů ve veřejných výdajích

**Vytvořeno pro Úřad vlády ČR jako součást projektu *Systémová podpora společné evropské politiky podpory a pomoci, ESI a obdobných fondů na Úřadu vlády ČR* (CZ.08.1.125/0.0/0.0/15_001/0000176)**

Relevantní předchozí publikace v této oblasti:

- [MMR (2017) o roli ESI fondů ve veřejných výdajích](https://dotaceeu.cz/cs/evropske-fondy-v-cr/narodni-organ-pro-koordinaci/evaluace/knihovna-evaluaci/verejne-vydaje-a-fondy-eu-2007%e2%80%932015) ( [PDF](https://dotaceeu.cz/Dotace/media/SF/NOK/Evaluace/Evalua%c4%8dn%c3%ad%20knihovna/2017/Adicionalita/Verejne-vydaje-a-fondy-EU-final-public_1.pdf))
- [Předchozí studie Úřadu vlády (2017) - makroekonomické odhady dopadu ESIF na ekonomiku](https://www.vlada.cz/assets/evropske-zalezitosti/analyzy-EU/171204_Dopad_ESI_fondu_na_hospodarsky_rust_CR_final.pdf)
- [Navazující studie Úřadu vlády (2018)](https://www.vlada.cz/assets/evropske-zalezitosti/analyzy-EU/Dopad-ESI-fondu-na-hospodarstvi-CR.pdf)
- [Úřad vlády (2019) přehled využívání makro modelů v zemích EU](https://www.vlada.cz/assets/evropske-zalezitosti/aktualne/Vyuzivani-makroevaluaci-a-makroekonomickych-modelu-clenskymi-staty-EU.pdf)
